apiVersion: apps/v1
kind: Deployment
metadata:
   name: completionapi-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: completionapi-prod
  strategry:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: completionapi-prod
    spec:
      containers:
      - name: completionapi-prod
        image: shehan97105/completionservice:latest
        ports:
        - containerPort: 5002

